#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@softwarecenter[-1]
	add ucitrack softwarecenter
	set ucitrack.@softwarecenter[-1].init=softwarecenter
	commit ucitrack
EOF

/etc/init.d/softwarecenter enable

rm -f /tmp/luci-indexcache
exit 0
