# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for cow B ping by wulishui
LUCI_DEPENDS:=+libc
LUCI_PKGARCH:=all
PKG_VERSION:=v1.2
PKG_RELEASE:=v1.2-20200210

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


