
include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-diskman
LUCI_DEPENDS:=+e2fsprogs +parted +smartmontools +blkid +btrfs-progs
PKG_VERSION:=v0.0.2
PKG_RELEASE:=beta
PKG_MAINTAINER:=lisaac <https://github.com/lisaac/luci-app-diskman>


include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature