#
# Copyright (C) 2019 Jianpeng Xiang (1505020109@mail.hnust.edu.cn)
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Software Center
LUCI_DEPENDS:=+softwarecenter
PKG_VERSION:=1.0.6

PKG_MAINTAINER:=Jianpeng Xiang <1505020109@mail.hnust.edu.cn>
PKG_LICENSE:=GPLv3

include ../luci.mk

# call BuildPackage - OpenWrt buildroot signature
