# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for white or black list by wulishui
LUCI_DEPENDS:=+ipset +libc
LUCI_PKGARCH:=all
PKG_VERSION:=2.0-20191231
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
