#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@smartinfo[-1]
	add ucitrack smartinfo
	set ucitrack.@smartinfo[-1].init=smartinfo
	commit ucitrack
#	delete firewall.smartinfo
#	set firewall.smartinfo=include
#	set firewall.smartinfo.type=script
#	set firewall.smartinfo.path=/var/etc/smartinfo.include
#	set firewall.smartinfo.reload=1
#	commit firewall
EOF

/usr/lib/smartinfo/smart_checker.sh
/usr/lib/smartinfo/smart_functions.sh
/usr/lib/smartinfo/smart_status.sh

rm -f /tmp/luci-indexcache
exit 0
