#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@appfilter[-1]
	add ucitrack appfilter
	set ucitrack.@appfilter[-1].init=appfilter
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache

exit 0
