#!/bin/sh

# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@serverchan[-1]
	add ucitrack serverchan
	set ucitrack.@serverchan[-1].init=serverchan
	commit ucitrack
EOF

# remove LuCI cache
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
