include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI page for IPK smartinfo
LUCI_DEPENDS:=+luci-lib-fs
PKG_VERSION:=1
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
