#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for the Docker
LUCI_DEPENDS:=+docker-ce +luci-lib-json
LUCI_PKGARCH:=all

PKG_MAINTAINER:=lisaac <https://github.com/lisaac/luci-app-dockerman>

include ../../luci.mk
# include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
