#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Open App Filter Module
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-appfilter
PKG_VERSION:=1.0
PKG_RELEASE:=2
LUCI_DEPENDS:=+kmod-oaf

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
