#!/bin/sh
# Copyright (C) 2007 OpenWrt.org

/etc/init.d/rtorrent enabled && {

	[ "$ACTION" = "ifup" ] && {
		/etc/init.d/rtorrent start
	}

	[ "$ACTION" = "ifdown" ] && {
		/etc/init.d/rtorrent stop
	}
	
}
