#
# Copyright (C) 2019 Jianpeng Xiang (1505020109@mail.hnust.edu.cn)
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Software Center
LUCI_DEPENDS:=+softwarecenter
PKG_VERSION:=1.0.6

PKG_MAINTAINER:=Jianpeng Xiang <1505020109@mail.hnust.edu.cn>
PKG_LICENSE:=GPLv3

#define Package/$(PKG_NAME)/postinst
#!/bin/sh
#chmod 0755 /etc/init.d/softwarecenter
#chmod 0755 /usr/bin/softwarecenter/check_available_size.sh
#chmod 0755 /usr/bin/softwarecenter/lib_functions.sh
#chmod 0755 /usr/bin/softwarecenter/mysql_install.sh
#chmod 0755 /usr/bin/softwarecenter/nginx_install.sh
#chmod 0755 /usr/bin/softwarecenter/website_list_for_luci.sh
#chmod 0755 /usr/bin/softwarecenter/website_manager.sh
#exit 0
#endef

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
